"""
test_query_context_llm.py
=========================
Inspection tool for the /analyze pipeline.

It reuses the REAL production code paths so what you see here is exactly what
the API does:
    1. build_mongo_query()      -> the MongoDB filter that gets executed
    2. fetch_fashion_records()  -> the documents pulled back from Mongo
    3. build_analysis_prompt()  -> the exact context string handed to Gemini

By default it does NOT call Gemini (no API cost) — it only shows what WOULD be
sent. Flip RUN_LLM = True to also fire the real model call and print its report.

Everything (query + retrieved records + exact LLM context) is written to ONE
report file so nothing scrolls off the terminal.

Run:
    python test_query_context_llm.py
"""

import asyncio
import json

from schemas import FashionQueryPayload
from mongo_query import build_mongo_query, fetch_fashion_records
from graph import build_analysis_prompt, extract_citation_metadata


# ---------------------------------------------------------------------------
# EDIT THIS: the request you want to inspect (mirrors the POST /analyze body)
# ---------------------------------------------------------------------------
PAYLOAD = FashionQueryPayload(
    source="vogue",
    designer="prada",
    collection="Spring-2026-ready-to-wear",
    function="trend_analysis&recommendation",
    focus_areas=["fabrics", "colors"],
    # Optional filters — leave as None for a blanket (unfiltered) search.
    colors=["red", "blue"],
    themes=None,
    fabrics=["wool"],
    item_styles=None,
)

# Set True to ALSO fire the real Gemini call and print its report (costs an API call).
RUN_LLM = False

# The complete inspection report (query + records + LLM context) is written here.
REPORT_FILE = "analyze_inspection_report.txt"

# Key fields shown in the quick per-record summary table.
SUMMARY_FIELDS = ["designer", "collection_name", "source", "theme", "fabric", "colors", "page_url"]


# ---------------------------------------------------------------------------
# Output helper: everything passed to out() goes BOTH to the terminal and to
# the report file, so the file is a complete record of the run.
# ---------------------------------------------------------------------------
_report_lines: list[str] = []


def out(text: str = "") -> None:
    print(text)
    _report_lines.append(text)


def section(title: str) -> None:
    out("")
    out("=" * 80)
    out(f"  {title}")
    out("=" * 80)


def _short(value, width: int = 70) -> str:
    """Compact a value to a single line no wider than `width`."""
    if isinstance(value, (list, dict)):
        value = json.dumps(value, ensure_ascii=False)
    text = str(value).replace("\n", " ")
    return text if len(text) <= width else text[: width - 1] + "…"


async def main() -> None:
    # ---- 1. The request payload -----------------------------------------
    section("1. PAYLOAD  (the /analyze request body you are inspecting)")
    out(json.dumps(PAYLOAD.model_dump(), indent=2, ensure_ascii=False))

    # ---- 2. The MongoDB query -------------------------------------------
    section("2. MONGODB QUERY  (exactly what build_mongo_query sends to Mongo)")
    query = build_mongo_query(PAYLOAD)
    out(json.dumps(query, indent=2, ensure_ascii=False))

    # ---- 3. What comes back from Mongo ----------------------------------
    records = await fetch_fashion_records(PAYLOAD)

    section(f"3a. RECORDS RETRIEVED — SUMMARY  ->  {len(records)} document(s)")
    if not records:
        out("  (no records matched — the LLM would receive the 'No records found' message)")
        _write_report()
        return

    for i, r in enumerate(records, 1):
        out(f"\n  [{i}] _id={r.get('_id')}")
        for field in SUMMARY_FIELDS:
            if field in r:
                out(f"      {field:<16}: {_short(r[field])}")

    # Full raw documents (so you can see EVERYTHING derived from Mongo)
    section("3b. RECORDS RETRIEVED — FULL RAW JSON (every field of every document)")
    out(json.dumps(records, indent=2, ensure_ascii=False, default=str))

    # ---- 4. Response body — the exact metadata /analyze returns (minus ai_report) ----
    meta = extract_citation_metadata(records)
    response_body = {
        "ai_report": "<generated by Gemini — shown in full in section 6 when RUN_LLM=True>",
        "sources": meta["sources"],
        "sources_count": meta["sources_count"],
        "designers": meta["designers"],
        "designers_count": meta["designers_count"],
        "page_urls": meta["page_urls"],
        "page_urls_count": meta["page_urls_count"],
        "runway_imgs": meta["runway_imgs"],
        "runway_imgs_count": meta["runway_imgs_count"],
        "total_records_analyzed": len(records),
    }
    section("4. RESPONSE BODY  (exactly what POST /analyze returns — ai_report filled in section 6)")
    out(json.dumps(response_body, indent=2, ensure_ascii=False))

    # ---- 5. The exact context sent to the LLM ---------------------------
    prompt = build_analysis_prompt(PAYLOAD, records)

    # Baseline for comparison: the naive approach — every field of every record, so
    # collection-level constants (summary, page_url, ...) get repeated in all N looks.
    raw_records = [{k: v for k, v in r.items() if k != "_id"} for r in records]
    raw_len = len(json.dumps(raw_records, indent=2, ensure_ascii=False, default=str))
    new_len = len(prompt)
    reduction = (1 - new_len / raw_len) * 100 if raw_len else 0.0

    section("5. EXACT CONTEXT SENT TO GEMINI  (build_analysis_prompt output)")
    out(f"  Raw records payload (every field repeated per look): {raw_len:>8,} chars  (~{raw_len // 4:,} tokens)")
    out(f"  Compacted context actually sent to Gemini          : {new_len:>8,} chars  (~{new_len // 4:,} tokens)")
    out(f"  Token reduction from compaction                    : {reduction:>7.1f}%")
    out("-" * 80)
    out(prompt)

    # ---- 6. Optionally run the real model -> print the COMPLETE response body ----
    if RUN_LLM:
        section("6. FULL RESPONSE BODY  (live POST /analyze result, incl. ai_report)")
        from graph import run_fashion_engine
        result = await run_fashion_engine(PAYLOAD)
        out(json.dumps(result.model_dump(), indent=2, ensure_ascii=False))
    else:
        section("6. FULL RESPONSE BODY — SKIPPED (RUN_LLM = False)")
        out("  The metadata portion of the response body is shown in section 4 above.")
        out("  Set RUN_LLM = True at the top of this file to fire Gemini and print the")
        out("  complete response body here (ai_report + all metadata), exactly as /analyze returns it.")

    _write_report()


def _write_report() -> None:
    with open(REPORT_FILE, "w", encoding="utf-8") as f:
        f.write("\n".join(_report_lines))
    print(f"\n>>> Full report (query + records + LLM context) written to: {REPORT_FILE}")


if __name__ == "__main__":
    asyncio.run(main())
