import { useEffect, useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import {
  Box,
  Typography,
  Button,
  Alert,
  Skeleton,
  Chip,
  LinearProgress,
  IconButton,
  TextField,
} from "@mui/material";
import ArrowBackIcon from "@mui/icons-material/ArrowBack";
import EditIcon from "@mui/icons-material/Edit";
import CheckIcon from "@mui/icons-material/Check";
import PictureAsPdfIcon from "@mui/icons-material/PictureAsPdf";
import { PageShell } from "../../components/PageShell";
import { MoodboardViewer } from "../../components/MoodboardViewer";
import { getCentoireAPI } from "../../lib/api/generated/client";
import type { Moodboard } from "../../lib/api/generated/model";

const api = getCentoireAPI();

export function MoodboardDetailPage() {
  const { id } = useParams<{ id: string }>();
  const navigate = useNavigate();
  const [moodboard, setMoodboard] = useState<Moodboard | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState("");
  const [editingName, setEditingName] = useState(false);
  const [nameValue, setNameValue] = useState("");
  const [polling, setPolling] = useState(false);

  async function load() {
    if (!id) return;
    try {
      const doc = await api.getApiV1MoodboardsId(id);
      setMoodboard(doc);
      setNameValue(doc.name);
      if (doc.status === "pending" || doc.status === "running") {
        setPolling(true);
        startPolling(id);
      }
    } catch {
      setError("Failed to load moodboard");
    } finally {
      setLoading(false);
    }
  }

  function startPolling(boardId: string) {
    const interval = setInterval(async () => {
      try {
        const doc = await api.getApiV1MoodboardsId(boardId);
        setMoodboard(doc);
        if (doc.status === "done" || doc.status === "error") {
          clearInterval(interval);
          setPolling(false);
        }
      } catch {
        clearInterval(interval);
        setPolling(false);
      }
    }, 2500);
  }

  // eslint-disable-next-line react-hooks/set-state-in-effect
  useEffect(() => { load(); }, [id]);

  async function saveName() {
    if (!id) return;
    await api.patchApiV1MoodboardsId(id, { name: nameValue });
    setEditingName(false);
    setMoodboard((prev) => prev ? { ...prev, name: nameValue } : prev);
  }

  function exportBrief() {
    if (!moodboard?.moodboard) return;
    const data = moodboard.moodboard as Record<string, unknown>;
    const name = moodboard.name || "Creative Brief";

    const palette = (data.palette as Array<{ hex: string; role?: string }> | undefined) ?? [];
    const keywords = (data.keywords as string[] | undefined) ?? [];
    const badges = ((data.badges ?? data.trend_badges) as Array<{ label: string; lifecycle_stage: string; confidence_score: number }> | undefined) ?? [];
    const narrative = data.narrative as string | undefined;

    const paletteHtml = palette.map(
      (s) => `<span style="display:inline-block;width:28px;height:28px;border-radius:4px;background:${s.hex};margin-right:6px;vertical-align:middle;border:1px solid #ddd" title="${s.role ?? s.hex}"></span>`
    ).join("");

    const html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8"/>
  <title>${name}</title>
  <style>
    body { font-family: Georgia, serif; max-width: 760px; margin: 40px auto; color: #1a1a1a; line-height: 1.6; }
    h1 { font-size: 26px; margin-bottom: 4px; }
    .meta { font-size: 12px; color: #666; margin-bottom: 32px; }
    h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 1px; color: #444; border-bottom: 1px solid #eee; padding-bottom: 6px; margin-top: 28px; }
    p { font-size: 14px; color: #333; }
    .keywords span { display:inline-block; border:1px solid #ccc; border-radius:12px; padding:2px 10px; font-size:12px; margin:3px; }
    .badge { display:inline-block; border:1px solid #999; border-radius:4px; padding:3px 8px; font-size:11px; margin:3px; }
    @media print { body { margin: 20px; } }
  </style>
</head>
<body>
  <h1>${name}</h1>
  <p class="meta">Generated by Centoire · ${new Date().toLocaleDateString()}</p>
  ${narrative ? `<h2>Creative Direction</h2><p>${narrative}</p>` : ""}
  ${palette.length > 0 ? `<h2>Color Palette</h2><p>${paletteHtml}</p>` : ""}
  ${keywords.length > 0 ? `<h2>Keywords</h2><div class="keywords">${keywords.map((k) => `<span>${k}</span>`).join("")}</div>` : ""}
  ${badges.length > 0 ? `<h2>Trend Signals</h2><div>${badges.map((b) => `<span class="badge">${b.label} · ${b.lifecycle_stage} · ${Math.round(b.confidence_score * 100)}%</span>`).join("")}</div>` : ""}
</body>
</html>`;

    const win = window.open("", "_blank");
    if (!win) return;
    win.document.write(html);
    win.document.close();
    win.focus();
    win.print();
  }

  if (loading) return (
    <PageShell title="Moodboard">
      <Skeleton variant="rectangular" height={400} sx={{ borderRadius: 2 }} />
    </PageShell>
  );

  if (error) return (
    <PageShell title="Moodboard">
      <Alert severity="error">{error}</Alert>
    </PageShell>
  );

  if (!moodboard) return null;

  return (
    <PageShell title="Moodboard">
      <Box sx={{ maxWidth: 1000, mx: "auto" }}>
        <Box sx={{ display: "flex", justifyContent: "space-between", alignItems: "center", mb: 2 }}>
          <Button
            startIcon={<ArrowBackIcon />}
            onClick={() => navigate("/moodboards")}
            size="small"
          >
            All Boards
          </Button>
          {moodboard.status === "done" && moodboard.moodboard && (
            <Button
              variant="outlined"
              size="small"
              startIcon={<PictureAsPdfIcon />}
              onClick={exportBrief}
            >
              Export as PDF
            </Button>
          )}
        </Box>

        <Box sx={{ display: "flex", alignItems: "center", gap: 1, mb: 1 }}>
          {editingName ? (
            <>
              <TextField
                value={nameValue}
                onChange={(e) => setNameValue(e.target.value)}
                size="small"
                autoFocus
                onKeyDown={(e) => e.key === "Enter" && saveName()}
              />
              <IconButton size="small" onClick={saveName} color="primary">
                <CheckIcon fontSize="small" />
              </IconButton>
            </>
          ) : (
            <>
              <Typography variant="h5" fontWeight={700}>
                {moodboard.name || "Untitled"}
              </Typography>
              <IconButton size="small" onClick={() => setEditingName(true)}>
                <EditIcon fontSize="small" />
              </IconButton>
            </>
          )}
          <Chip
            label={moodboard.status}
            size="small"
            color={moodboard.status === "done" ? "success" : moodboard.status === "error" ? "error" : "default"}
          />
        </Box>

        {polling && (
          <Box sx={{ mb: 3 }}>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 1 }}>
              Still generating — checking for updates…
            </Typography>
            <LinearProgress />
          </Box>
        )}

        {moodboard.status === "error" && (
          <Alert severity="error" sx={{ mb: 3 }}>Generation failed: {moodboard.error}</Alert>
        )}

        {moodboard.status === "done" && moodboard.moodboard && (
          <MoodboardViewer data={moodboard.moodboard as Parameters<typeof MoodboardViewer>[0]["data"]} />
        )}
      </Box>
    </PageShell>
  );
}
